#!/bin/sh
#
# SPDX-License-Identifier: CC0-1.0

## Heads up. This script is supposed to be run from the directory in
## which it was found.

# start guile interactive with current directory added to the
# load-path.
guile -L .
